gOtherText_NewName:: @ 81C574F
    .string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
    .string "KHAIRAT$"

gNameChoice_Red:: @ 81C575E
    .string "UROOJ$"

gNameChoice_Leaf:: @ 81C5762
    .string "ZUHA$"

gNameChoice_Fire:: @ 81C5767
    .string "SAYDA$"

gNameChoice_Gary:: @ 81C576C
    .string "ZARQAWI$"

gNameChoice_Kaz:: @ 81C5771
    .string "YAQOOB$"

gNameChoice_Toru:: @ 81C5775
    .string "SIRAJ$"

gNameChoice_Ash:: @ 81C577A
    .string "JUNAID$"

gNameChoice_Kene:: @ 81C577E
    .string "ZALMAIY$"

gNameChoice_Geki:: @ 81C5783
    .string "QAMAR$"

gNameChoice_Jak:: @ 81C5788
    .string "ISRAR$"

gNameChoice_Janne:: @ 81C578C
    .string "JALEEL$"

gNameChoice_Jonn:: @ 81C5792
    .string "HURR$"

gNameChoice_Kamon:: @ 81C5797
    .string "UZAIR$"

gNameChoice_Karl:: @ 81C579D
    .string "LUGHAAT$"

gNameChoice_Taylor:: @ 81C57A2
    .string "QULDAIR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "ZABEEH$"

gNameChoice_Hiro:: @ 81C57AF
    .string "MAHMUD$"

gNameChoice_Max:: @ 81C57B4
    .string "GHALIB$"

gNameChoice_Jon:: @ 81C57B8
    .string "MIR$"

gNameChoice_Ralph:: @ 81C57BC
    .string "IQBAL$"

gNameChoice_Kay:: @ 81C57C2
    .string "MUSTAFA$"

gNameChoice_Tosh:: @ 81C57C6
    .string "ISRAT$"

gNameChoice_Roak:: @ 81C57CB
    .string "HUMAYUN$"

gNameChoice_Omi:: @ 81C57D0
    .string "BUS$"

gNameChoice_Jodi:: @ 81C57D4
    .string "ARZOO$"

gNameChoice_Amanda:: @ 81C57D9
    .string "ZULEKHA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "ZHAALA$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAHBUBA$"

gNameChoice_Michi:: @ 81C57EE
    .string "SHUKRIA$"

gNameChoice_Paula:: @ 81C57F4
    .string "QADIRA$"

gNameChoice_June:: @ 81C57FA
    .string "TALEEHA$"

gNameChoice_Cassie:: @ 81C57FF
    .string "BENAZIR$"

gNameChoice_Rey:: @ 81C5806
    .string "ZUBI$"

gNameChoice_Seda:: @ 81C580A
    .string "RAHEELA$"

gNameChoice_Kiko:: @ 81C580F
    .string "RASHIDA$"

gNameChoice_Mina:: @ 81C5814
    .string "SAMIA$"

gNameChoice_Norie:: @ 81C5819
    .string "SHAGHF$"

gNameChoice_Sai:: @ 81C581F
    .string "NAJHA$"

gNameChoice_Momo:: @ 81C5823
    .string "FAEEZAH$"

gNameChoice_Suzi:: @ 81C5828
    .string "SHAZFA$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gNewGame_HelpDocs2:: @ 81C5875
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gNewGame_HelpDocs4:: @ 81C58F9
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gNewGame_HelpDocs5:: @ 81C592B
    .string "Press this button to open the\n"
    .string "MENU.$"

gNewGame_HelpDocs6:: @ 81C594F
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gNewGame_HelpDocs7:: @ 81C5981
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Which character\n"
    .string "would you like to play as?$"

gNewGameAdventureIntro1::
    .string "Welcome to Pokemon Garbage Green!\n"
	.string "This is a ROM Hack that aims to\n"
	.string "make Leaf Green much harder by\n" 
	.string "only giving the player underused \n"
	.string "and weak Pokemon.\n"
	.string "\n"
	.string "Additionally, some Pokemon evolve\n"
	.string "later than usual or not at all.$"

gNewGameAdventureIntro2::
    .string "Items can't be used in battle and\n"
    .string "your Pokemons leveling will be\n"
    .string "limited.\n"
    .string "Check the documentation file for\n"
    .string "more details.\n"
    .string "This game is intended to be\n"
    .string "played as a Nuzlocke, but this is\n"
	.string "not required.$"

gNewGameAdventureIntro3::
    .string "If you have further questions\n"
    .string "about the game or would like to\n"
    .string "share your progress join my\n"
    .string "Discord at discord.gg/pchal.\n"
    .string "Thank you to my community members\n"
    .string "who helped to create this game,\n"
    .string "I hope you love playing it as\n"
	.string "much as I loved making it!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gOakText_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pMake sure to follow\n"
    .string "twitch.tv/pokemonchallenges!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
