SilphCo_1F_Text_WelcomePresidentInBoardroom:: @ 81754F7
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile:: @ 817552A
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign:: @ 8175549
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"

SilphCo_1F_Text_CriticalInfo::
    .string "I have critical information!$"

SilphCo_1F_Text_LockYouInText::
    .string "TEAM ROCKET took a bunch of\n"
    .string "SILPH CO. workers hostage and\l"
    .string "reprogrammed our warp panels.\p"
    .string "It appears as if this one only\n"
    .string "goes one way, so you'll probably\l"
    .string "be locked in until you beat them!$"

SilphCo_1F_Text_PostRocketScientist::
    .string "Thank you so much for saving us!\p"
    .string "Unfortunately, I've realized\n"
    .string "that I'm not as good at my job\l"
    .string "as you are at yours.\p"
    .string "I still haven't figured out how\n"
    .string "to fix the warp panels, the\l"
    .string "elevator, or anything else.$"









