CinnabarIsland_Gym_Text_BlaineIntro:: @ 8199543
    .string "Hah!\p"
    .string "I am BLAINE, the red-hot LEADER\n"
    .string "of CINNABAR GYM!\p"
    .string "My fiery POKéMON are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "You better have BURN HEAL!{PLAY_BGM}{MUS_EXEYE}$"

CinnabarIsland_Gym_Text_BlaineDefeat:: @ 81995FA
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove:: @ 8199652
    .string "FIRE BLAST is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on WATER POKéMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge:: @ 819969E
    .string "Hah!\p"
    .string "The VOLCANOBADGE heightens the\n"
    .string "SPECIAL stats of your POKéMON.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine:: @ 81996FF
    .string "{PLAYER} received TM38\n"
    .string "from BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle:: @ 819971D
    .string "TM38 contains FIRE BLAST.\n"
    .string "Teach it to FIRE-type POKéMON.\p"
    .string "VULPIX or CHARMELEON would be\n"
    .string "ideal for that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis:: @ 8199789
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro:: @ 81997A5
    .string "Do you know how hot POKéMON fire\n"
    .string "breath can get?$"

CinnabarIsland_Gym_Text_ErikDefeat:: @ 81997D6
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle:: @ 81997EA
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro:: @ 819983F
    .string "I was a thief, but I went straight\n"
    .string "as a TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat:: @ 8199870
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle:: @ 819987D
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's POKéMON.$"

CinnabarIsland_Gym_Text_AveryIntro:: @ 81998BD
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat:: @ 81998ED
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle:: @ 8199911
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro:: @ 8199948
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat:: @ 8199973
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle:: @ 8199986
    .string "I wish there were a thief POKéMON.\n"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro:: @ 81999B7
    .string "I know why BLAINE became a\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat:: @ 81999DB
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle:: @ 81999DF
    .string "Our LEADER, BLAINE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed BLAINE to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro:: @ 8199A7F
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat:: @ 8199AB9
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle:: @ 8199AC9
    .string "PONYTA, NINETALES…\n"
    .string "Those are popular FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro:: @ 8199AFC
    .string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat:: @ 8199B16
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle:: @ 8199B27
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the FIRE\n"
    .string "type beats ICE-type POKéMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice:: @ 8199B81
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded BLAINE is a FIRE\n"
    .string "POKéMON pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "BURN HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory:: @ 8199C0C
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue:: @ 8199C29
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon:: @ 8199C62
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules:: @ 8199C9F
    .string "POKéMON Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a TRAINER!\p"
    .string "If you want to conserve your\n"
    .string "POKéMON for the GYM LEADER…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1:: @ 8199D5A
    .string "Does SKITTY need a MOON STONE\n"
	.string "to evolve?$"

CinnabarIsland_Gym_Text_QuizQuestion2:: @ 8199D79
    .string "Does POLIWAG evolve into POLIWHIRL?$"

CinnabarIsland_Gym_Text_QuizQuestion3:: @ 8199DA9
    .string "Can you get TM36 SLUDGE BOMB\n"
    .string "before beating the ELITE 4?$"

CinnabarIsland_Gym_Text_QuizQuestion4:: @ 8199DC6
    .string "Is SURF a good MOVE?$"

CinnabarIsland_Gym_Text_QuizQuestion5:: @ 8199E00
    .string "Have you figured out how to\n"
    .string "sweep LANCE with BEAUTIFLY yet?$"

CinnabarIsland_Gym_Text_QuizQuestion6:: @ 8199E36
    .string "Where did you come from?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough:: @ 8199E4F
    .string "You're absolutely correct!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_Quiz1BattleText:
	.string "Usually yes, but not in\n"
	.string "this game!\p"
	.string "Prepare to battle!$"

CinnabarIsland_Gym_Text_Quiz2BattleText:
	.string "The Council of Kanto disabled\n"
	.string "the evolution because POLIWHIRL\l"
	.string "was too powerful.\p"
	.string "So yes, but actually no.\p"
	.string "Battle time!$"

CinnabarIsland_Gym_Text_Quiz3BattleText:
	.string "The best answer for everything\n"
	.string "in life is, “it depends”, but\l"
	.string "it wasn't even an option to\l"
	.string "get out of battling me!$"

CinnabarIsland_Gym_Text_Quiz4BattleText:
	.string "HAHAHAHAHAHAHAHAHAHAHAH!$"

CinnabarIsland_Gym_Text_Quiz4BattleTextNo:
	.string "\p"
	.string "HA!$"

CinnabarIsland_Gym_Text_Quiz5BattleText:
	.string "You should definitely look\n"
	.string "harder at your strategies then.$"

CinnabarIsland_Gym_Text_Quiz6BattleText:
	.string "That doesn't make any sense.\p"
	.string "You have to come from somewhere\p"
	.string "Battle me, anyway.$"

CinnabarIsland_Gym_Text_SorryBadCall:: @ 8199E79
    .string "Sorry!\n"
    .string "Bad call!$"

CinnabarIsland_Gym_Text_HaveToCheckParty:
	.string "Checking Party Size!$"

CinnabarIsland_Gym_Text_GoAhead:
	.string "You may now enter the GYM.$"

CinnabarIsland_Gym_Text_CantLetYouIn:
	.string "ERROR: More than three POKéMON\n"
	.string "in party.\p"
	.string "Come back with fewer POKéMON.$"

CinnabarIsland_Gym_Text_CannotLeave:
	.string "You may not leave until you have\n"
	.string "defeated BLAINE.$"

