PokemonTower_2F_Text_RivalIntro:: @ 8179CFF
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "What brings you here?\l"
    .string "Is your POKéMON dead?\p"
    .string "Hey! It's alive!\p"
    .string "I can at least make them faint!\n"
    .string "Let's go!$"

PokemonTower_2F_Text_RivalDefeat:: @ 8179D73
    .string "What?\n"
    .string "You stinker!\p"
    .string "I took it easy on you, too!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory:: @ 8179DA2
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle:: @ 8179DD4
    .string "How's your POKéDEX coming?\n"
    .string "I just caught a LILEEP!\p"
    .string "I can't find the bigger CRADILY.\n"
    .string "Where could they be?\p"
    .string "I bet there aren't any left!\p"
    .string "Well, I better get going.\n"
    .string "I've got a lot to accomplish,\l"
    .string "unlike you.\p"
    .string "Smell ya later!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts:: @ 8179EAE
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "A SILPH SCOPE might be able to\n"
    .string "unmask them.$"

PokemonTower_2F_Text_Gatekeeper_LockIn::
    .string "I cannot allow you to abandon\n"
    .string "us until you have quelled the\l"
    .string "restless spirits.$"

PokemonTower_2F_Text_Gatekeeper_NeedHelp::
    .string "Oh!\p"
    .string "I see you have a SILPH SCOPE.\p"
    .string "We need your help to purge our\n"
    .string "tower of rampaging spirits.\p"
    .string "However, I cannot let you leave\n"
    .string "after you enter.\p"
    .string "Will you help us?$"

PokemonTower_2F_Text_Gatekeeper_GoodLuck::
    .string "Thank you and good luck.$"

PokemonTower_2F_Text_Gatekeeper_Prepare::
    .string "Prepare yourself.\p"
    .string "Then come back.  You do not\n"
    .string "want me to hunt you down if\l"
    .string "you do not return.$"

    



