ViridianCity_Mart_Text_YouCameFromPallet:: @ 819021A
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak:: @ 819023A
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk:: @ 8190289
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe:: @ 81902BF
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes:: @ 81902F5
    .string "The shops in Kanto recently\n"
    .string "fell under new management.\p"
    .string "The new owners must be pretty\n"
    .string "sadistic to stop selling\n"
    .string "ANTIDOTES.$"


ViridianCity_Mart_Text_GotToBuySomePotions:: @ 819032C
    .string "You can't buy any POTIONS here.\p"
    .string "You'll never be able to help\n"
    .string "when your POKéMON need quick\n"
    .string "healing.$"

